const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 8000,
      img: './images/item-1.jpeg',
      desc: ` Proin ullamcorper dignissim augue, non interdum orci porttitor id. Duis rutrum metus nulla, sed posuere eros interdum eu. `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 12000,
      img: './images/item-2.jpeg',
      desc: `Phasellus aliquet lacinia dolor a pharetra. Phasellus faucibus odio non neque porttitor, id laoreet lorem varius. Fusce pharetra ligula velit, vel egestas sapien dignissim vel`,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 3500,
      img: './images/item-3.jpeg',
      desc: `Nunc tincidunt aliquam risus ac posuere. Curabitur vel efficitur risus, non vehicula est. Nulla non semper ligula, eu porta est. `,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 15000,
      img: './images/item-4.jpeg',
      desc: `Aliquam arcu justo, imperdiet a fringilla vitae, dignissim vel dolor. Quisque at pulvinar leo, quis cursus mi. Nullam elit ex, tempus a tincidunt et `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 2800,
      img: './images/item-5.jpeg',
      desc: `Aliquam arcu justo, imperdiet a fringilla vitae, dignissim vel dolor. Quisque at pulvinar leo, quis cursus mi. Nullam elit ex, tempus a tincidunt et `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 1200,
      img: './images/item-6.jpeg',
      desc: `Duis interdum fermentum leo, at tincidunt risus cursus quis. Aliquam suscipit, dolor quis consequat cursus, dui nisl imperdiet mauris,`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 9000,
      img: './images/item-7.jpeg',
      desc: `Duis interdum fermentum leo, at tincidunt risus cursus quis. Aliquam suscipit, dolor quis consequat cursus, dui nisl imperdiet mauris, `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 4000,
      img: './images/item-8.jpeg',
      desc: `Duis interdum fermentum leo, at tincidunt risus cursus quis. Aliquam suscipit, dolor quis consequat cursus, dui nisl imperdiet mauris`,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 8500,
      img: './images/item-9.jpeg',
      desc: `Vestibulum scelerisque finibus purus, vel maximus felis iaculis sed.`,
    },
  ];
  export default menu;